version: "3.8"

services:
  # Service for Azure Functions
  azure-functions:
    platform: linux/arm64/v8
    build:
      context: . # Context for the build, set to the current directory
      dockerfile: Dockerfile # Specifies the Dockerfile to use
    ports:
      - "8080:80" # Maps port 80 inside the container to port 8080 on the host
    environment:
      AzureWebJobs_FileWatchingEnabled: "false" # Disables file watching for dynamic updates
      AzureFunctionsWebHost__IsFileSystemReadOnly: "True" # Sets file system to read-only
      AzureWebJobsScriptRoot: "/home/site/wwwroot" # Sets the script root directory
      AzureFunctionsJobHost__Logging__Console__IsEnabled: "true" # Enables console logging
      # Add additional environment variables here as needed

  # Service for Nginx
  nginx:
    image: nginx:latest # Uses the latest Nginx image
    ports:
      - "80:80" # Maps port 80 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mounts nginx.conf from host to container as read-only
    depends_on:
      - azure-functions # Specifies that Nginx depends on the azure-functions service
